### ISSUE TITLE
Add documentation for Security configuration

### ISSUE THREAD

**Issue by mvanderlee** [aparo/opensearch-prometheus-exporter#4]
It would be great if you could expand upon this with an example config of a role with minimum permissions needed to access the metrics endpoint.

> If you enable security in OpenSearch, remember to set up the credentials also in Prometheus configuration.

**Comment by BlackMetalz** [comment]
Update for anyone who has no idea about Prometheus config
```
  - job_name: opensearch
    scrape_interval: 30s
    metrics_path: "/_prometheus/metrics"
    static_configs:
    - targets:
      - ip:9200
    basic_auth:
      username: 'user'
      password: 'pass'
```
and setup user with info via Dashboard
```
metrics_access:
  reserved: true
  cluster_permissions:
    - 'cluster_monitor'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'indices_monitor'
```
